version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-postgres
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    image: okhotinaks/foodgram_backend
    env_file: .env
    volumes:
      - ./data:/app/data
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: okhotinaks/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    container_name: foodgram-proxy
    image: okhotinaks/foodgram_gateway
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles
      - media:/app/media
    depends_on:
      - backend
      - frontend
