# Generated by Django 3.2 on 2025-03-17 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['author'], 'verbose_name': 'Подпискa', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscribe_unique',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'Такой адрес уже зарегистрирован.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры и символы @/./+/-/_.', regex='^[\\w.@+-]+\\z')], verbose_name='Адрес электронной почты'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='user_author_unique'),
        ),
    ]
